### ISSUE TITLE
Site Crashed when installed - 4.0

### ISSUE THREAD

**Issue by js-restaurantlink** [nopSolutions/taxjar-plugin-for-nopcommerce#1]
When I installed TaxJar in my Nop Commerce 4.0 site - the whole site crashed.  Here is the log file.  Can you see anything that might have caused it?

Thanks,

Jeff
js@restaurantlink.com

[stdout_4968_2018227203730.log](https://github.com/nopSolutions/taxjar-plugin-for-nopcommerce/files/1767197/stdout_4968_2018227203730.log)

**Comment by skoshelev** [comment]
Closed #1 (https://github.com/nopSolutions/taxjar-plugin-for-nopcommerce/commit/e030710473ec07cd845d759aa5037a4e6db48c98)
